{% set name = "qt-command-palette" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qt_command_palette-{{ version }}.tar.gz
  sha256: cf6f0692bfd26345b677422c263f3697c8ad71bb2c56165f35d9ddfe51c81636

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - qtpy >=2.0.0

test:
  imports:
    - qt_command_palette
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/qt-command-palette
  summary: A command palette widget for Qt applications
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/hanjinliu/qt-command-palette

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinlu
